### ISSUE TITLE
Snakebite - Step 2

### ISSUE THREAD

**Issue by SolangaM** [joshlongbottom/snakebite#1]
Hi,
I've got an issue in the second step plot_occurrence_spocc.R 
From where can I download the .shp files you mentioned in the code?

**Comment by joshuarcarter** [comment]
The shapefile referenced (admin2013_0.shp) is derived from the FAO Global Administrative Unit Layers (GAUL) project, specifically [“G2015_2013"](http://www.fao.org/geonetwork/srv/en/metadata.show%3Fid%3D12691). 

The other files, “Africa.shp”, “Latin_America.shp”, “USA_MEX.shp” are subsets from the “admin2013_0.shp”, that you can recreate by subsetting by an index of ISO3 codes for each region.

I have also included a link to the digitised [WHO range shapefiles](https://drive.google.com/open?id=1S8F_IrPSO_yRBk9YRXXqbIu90JfqLGB9), as you may also need these.
